### ISSUE TITLE
It doesn't start

### ISSUE THREAD

**Issue by americodias** [mammuth/kindle-clippings#52]
Hello all,

I was trying to test this software. However I'm unable to make it start.

When I run "docker-composer up" I get the following errors:

```
 web The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested      0.0s
Attaching to kindle-clippings-db-1, kindle-clippings-web-1
kindle-clippings-db-1   | Error: Database is uninitialized and superuser password is not specified.
kindle-clippings-db-1   |        You must specify POSTGRES_PASSWORD to a non-empty value for the
kindle-clippings-db-1   |        superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
kindle-clippings-db-1   |
kindle-clippings-db-1   |        You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
kindle-clippings-db-1   |        connections without a password. This is *not* recommended.
kindle-clippings-db-1   |
kindle-clippings-db-1   |        See PostgreSQL documentation about "trust":
kindle-clippings-db-1   |        https://www.postgresql.org/docs/current/auth-trust.html
kindle-clippings-db-1   |
kindle-clippings-db-1 exited with code 1
kindle-clippings-web-1  | /app/addons/aldryn-django/aldryn_config.py:131: RuntimeWarning: no cache configured. Falling back to CACHE_URL=locmem://
kindle-clippings-web-1  |   RuntimeWarning,
kindle-clippings-web-1  | /app/addons/aldryn-django/aldryn_config.py:131: RuntimeWarning: no cache configured. Falling back to CACHE_URL=locmem://
kindle-clippings-web-1  |   RuntimeWarning,
kindle-clippings-web-1  | Performing system checks...
kindle-clippings-web-1  |
kindle-clippings-web-1  |
kindle-clippings-web-1  | System check identified no issues (0 silenced).
kindle-clippings-web-1  | Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x400f2bfe18>
kindle-clippings-web-1  | Traceback (most recent call last):
kindle-clippings-web-1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
kindle-clippings-web-1  |     self.connect()
kindle-clippings-web-1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect
kindle-clippings-web-1  |     self.connection = self.get_new_connection(conn_params)
kindle-clippings-web-1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
kindle-clippings-web-1  |     connection = Database.connect(**conn_params)
kindle-clippings-web-1  |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
kindle-clippings-web-1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
kindle-clippings-web-1  | psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known
kindle-clippings-web-1  |
kindle-clippings-web-1  |
kindle-clippings-web-1  |
kindle-clippings-web-1  | The above exception was the direct cause of the following exception:
kindle-clippings-web-1  |
kindle-clippings-web-1  |
kindle-clippings-web-1  | Traceback (most recent call last):
kindle-clippings-web-1  |   File "/usr/local/lib/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
kindle-clippings-web-1  |     fn(*args, **kwargs)
kindle-clippings-web-1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 127, in inner_run
kindle-clippings-web-1  |     self.check_migrations()
kindle-clippings-web-1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 422, in check_migrations
kindle-clippings-web-1  |     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
kindle-clippings-web-1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 20, in __init__
kindle-clippings-web-1  |     self.loader = MigrationLoader(self.connection)
kindle-clippings-web-1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 52, in __init__
kindle-clippings-web-1  |     self.build_graph()
kindle-clippings-web-1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 210, in build_graph
kindle-clippings-web-1  |     self.applied_migrations = recorder.applied_migrations()
kindle-clippings-web-1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
kindle-clippings-web-1  |     self.ensure_schema()
kindle-clippings-web-1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
kindle-clippings-web-1  |     if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
kindle-clippings-web-1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 254, in cursor
kindle-clippings-web-1  |     return self._cursor()
kindle-clippings-web-1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 229, in _cursor
kindle-clippings-web-1  |     self.ensure_connection()
kindle-clippings-web-1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
kindle-clippings-web-1  |     self.connect()
kindle-clippings-web-1  |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
kindle-clippings-web-1  |     six.reraise(dj_exc_type, dj_exc_value, traceback)
kindle-clippings-web-1  |   File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
kindle-clippings-web-1  |     raise value.with_traceback(tb)
kindle-clippings-web-1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
kindle-clippings-web-1  |     self.connect()
kindle-clippings-web-1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect
kindle-clippings-web-1  |     self.connection = self.get_new_connection(conn_params)
kindle-clippings-web-1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
kindle-clippings-web-1  |     connection = Database.connect(**conn_params)
kindle-clippings-web-1  |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
kindle-clippings-web-1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
kindle-clippings-web-1  | django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known
kindle-clippings-web-1  |
kindle-clippings-web-1  |
```

Does anyone has any ideias on how to fix this?

Thanks in advance,
Américo

**Comment by mammuth** [comment]
Hi, you could try the changes in https://github.com/mammuth/kindle-clippings/pull/27

**Comment by mammuth** [comment]
I know this is a very old issue but I finally found some time to revisit the project setup and the documentation.

It _should_ work nicely now to spin up the project 🙏
